[default.probe]
protocol = "Swd"
#speed = 20000
# If you only have one probe cargo embed will pick automatically
# Otherwise: add your probe's VID/PID/serial to filter

## rust-dap
# usb_vid = "6666"
# usb_pid = "4444"
# serial = "test"


[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = true

[default.general]
chip = "RP2040_SELFDEBUG"
log_level = "WARN"
# RP2040 does not support connect_under_reset
connect_under_reset = false

[default.rtt]
enabled = true
#up_mode = "NoBlockSkip"
#channels = [{ up = 0, down = 0, up_mode = "NoBlockSkip", format = "Defmt" }]
timeout = 12000
show_timestamps = true
log_enabled = true
log_path = "./logs"

[default.gdb]
enabled = false
#gdb_connection_string = "127.0.0.1:2345"
