[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040_SELFDEBUG"
# runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

[env]
# DEFMT_LOG = "debug"
