[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040_SELFDEBUG"
#runner = "probe-run --chip RP2040_SELFDEBUG"
# runner = "probe-rs-cli run --chip RP2040_SELFDEBUG"
# runner = "elf2uf2-rs -d"
#runner = "cargo embed --chip RP2040_SELFDEBUG --probe 1209:2488"
# rustflags = [
#     "-C",
#     "linker=flip-link",
#     "-C",
#     "link-arg=--nmagic",
#     "-C",
#     "link-arg=-Tdefmt.x",

#     # Code-size optimizations.
#     #   trap unreachable can save a lot of space, but requires nightly compiler.
#     #   uncomment the next line if you wish to enable it
#     # "-Z", "trap-unreachable=no",
#     "-C",
#     "inline-threshold=5",
#     "-C",
#     "no-vectorize-loops",
# ]


[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
#DEFMT_LOG = "trace"
